# Generated by Django 4.1.2 on 2022-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_cantidad_alter_menu_imagen'),
    ]

    operations = [

        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
