# Generated by Django 4.1.2 on 2022-10-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_cantidad_alter_menu_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cantidad',
        ),
    ]
