# Generated by Django 4.1.2 on 2022-10-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('cadete', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateField()),
                ('estadoPedido', models.IntegerField(choices=[('1', 'Pendiente'), ('2', 'En preparación'), ('3', 'En camino'), ('4', 'Entregado'), ('5', 'Devuelto'), ('6', 'Cancelado')])),
                ('comentario', models.TextField(blank=True)),
                ('envioDomicilio', models.CharField(max_length=25)),
                ('tiempoDemora', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cadete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadete.cadete')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('menu', models.ManyToManyField(to='menu.menu')),
            ],
        ),
    ]
