# Generated by Django 4.1.2 on 2022-10-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_pedido_enviodomicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estadoPedido',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En preparación'), (3, 'En camino'), (4, 'Entregado'), (5, 'Devuelto'), (6, 'Cancelado')]),
        ),
    ]
