# Generated by Django 4.1.2 on 2022-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_pedido_estadopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
