# Generated by Django 4.1.2 on 2022-11-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadete', '0002_alter_cadete_codigozona'),
        ('administrador', '0006_alter_pedido_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cadete',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cadete.cadete'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tiempoDemora',
            field=models.IntegerField(blank=True),
        ),
    ]
