# Generated by Django 4.1.2 on 2022-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadete',
            name='codigoZona',
            field=models.IntegerField(),
        ),
    ]
