# Generated by Django 4.1.2 on 2022-10-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_domicilio_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='domicilio_calle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio_numero',
            field=models.IntegerField(null=True),
        ),
    ]
