# Generated by Django 4.1.2 on 2022-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_domicilio_calle_cliente_domicilio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_calle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_numero',
            field=models.IntegerField(),
        ),
    ]
